[[main]]
  name = "ホーム"
  pageRef = "/"
  weight = 10

[[main]]
  name = "アプリ"
  pageRef = "apps"
  weight = 20

[[main]]
  name = "ブログ"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "概要"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "サポート"
  pageRef = "support"
  weight = 10

[[footer]]
  name = "プライバシー"
  pageRef = "privacy"
  weight = 20
