[[main]]
  name = "首頁"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Apps"
  pageRef = "apps"
  weight = 20

[[main]]
  name = "部落格"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "關於"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "支援"
  pageRef = "support"
  weight = 10

[[footer]]
  name = "隱私政策"
  pageRef = "privacy"
  weight = 20
